# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-26 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190626_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='booktest', verbose_name='图片'),
        ),
    ]
